### ISSUE TITLE
Unlabeled Data?

### ISSUE THREAD

**Issue by ccsasuke** [xrc10/cross-distill#1]
Hi,

In the data download link (http://nyc.lti.cs.cmu.edu/datasets/cross_distill.tar.gz), it seems the unlabeled data is not provided? Can we also have the unlabeled reviews?

**Comment by xrc10** [comment]
Please refer to the original dataset released in "Cross-Language Text Classification using Structural Correspondence Learning." by Peter Prettenhofer and Benno Stein.

**Comment by ccsasuke** [comment]
I guess those were not tokenized?

But anyway, I ended up taking the original dataset and used my own tokenizers. Closing for now.
It would be nice you also share the unlabeled data with the same tokenizations you used though.
